version: '3'
services:
  react-service:
    container_name: hyperapp-test-compose
    build: ./
    ports:
      - '3333:8080' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'

